[package]
name = "hash"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chksum-md5 = "0.0.0"
md5 = "0.7.0"
sha2 = "0.10.5"
